import type { MelodyVariation } from '@/types'

export const mockMelodyVariations: MelodyVariation[] = [
  {
    id: 'melody-1',
    qualityScore: 93,
    explanation:
      'An ascending arch contour that peaks on bar 3, using chromatic passing tones between scale degrees 6 and 7 for tension. The melody breathes — long sustained notes on strong beats, quick runs on weaker subdivisions. Every note choice traces the underlying Dorian harmony without being predictable.',
    emotionTags: ['melancholic', 'hopeful', 'searching'],
    contour: 'arch',
    articulation: 'legato',
    notes: [
      { pitch: 62, startBeat: 0, duration: 1, velocity: 85 },
      { pitch: 65, startBeat: 1, duration: 0.5, velocity: 78 },
      { pitch: 67, startBeat: 1.5, duration: 0.5, velocity: 82 },
      { pitch: 69, startBeat: 2, duration: 1, velocity: 90 },
      { pitch: 71, startBeat: 3, duration: 0.5, velocity: 80 },
      { pitch: 72, startBeat: 3.5, duration: 1.5, velocity: 95 },
      { pitch: 74, startBeat: 5, duration: 1, velocity: 88 },
      { pitch: 72, startBeat: 6, duration: 0.5, velocity: 80 },
      { pitch: 69, startBeat: 6.5, duration: 0.5, velocity: 75 },
      { pitch: 67, startBeat: 7, duration: 1, velocity: 70 },
    ],
  },
  {
    id: 'melody-2',
    qualityScore: 88,
    explanation:
      'A wave contour — descends into the minor third, climbs through the fifth, dips back. The staccato articulation creates rhythmic momentum, like a question being asked repeatedly. Syncopated hits land off the 4th beat creating forward propulsion. Chord tones hit on beats 1 and 3 anchor it harmonically.',
    emotionTags: ['driven', 'urgent', 'rhythmic'],
    contour: 'wave',
    articulation: 'staccato',
    notes: [
      { pitch: 74, startBeat: 0, duration: 0.25, velocity: 90 },
      { pitch: 72, startBeat: 0.5, duration: 0.25, velocity: 85 },
      { pitch: 69, startBeat: 1, duration: 0.5, velocity: 92 },
      { pitch: 67, startBeat: 1.75, duration: 0.25, velocity: 80 },
      { pitch: 69, startBeat: 2, duration: 0.25, velocity: 88 },
      { pitch: 71, startBeat: 2.5, duration: 0.5, velocity: 85 },
      { pitch: 72, startBeat: 3, duration: 0.25, velocity: 90 },
      { pitch: 74, startBeat: 3.5, duration: 0.5, velocity: 92 },
      { pitch: 72, startBeat: 4, duration: 0.25, velocity: 86 },
      { pitch: 69, startBeat: 4.5, duration: 0.5, velocity: 88 },
      { pitch: 67, startBeat: 5, duration: 1, velocity: 80 },
      { pitch: 65, startBeat: 6, duration: 0.5, velocity: 78 },
      { pitch: 67, startBeat: 6.75, duration: 0.25, velocity: 82 },
      { pitch: 69, startBeat: 7, duration: 1, velocity: 85 },
    ],
  },
  {
    id: 'melody-3',
    qualityScore: 85,
    explanation:
      'Angular contour with unexpected leaps — a minor 7th jump in bar 2, a tritone in bar 4. Defies expectation. The melody establishes a comfortable pattern then breaks it. This creates the emotional impact of surprise — ideal for a counter-melody that should feel slightly alien over familiar chords.',
    emotionTags: ['surprising', 'intellectual', 'tense'],
    contour: 'angular',
    articulation: 'mixed',
    notes: [
      { pitch: 62, startBeat: 0, duration: 1, velocity: 85 },
      { pitch: 60, startBeat: 1, duration: 0.5, velocity: 80 },
      { pitch: 72, startBeat: 1.5, duration: 0.5, velocity: 92 },
      { pitch: 69, startBeat: 2, duration: 1, velocity: 88 },
      { pitch: 65, startBeat: 3, duration: 0.25, velocity: 78 },
      { pitch: 68, startBeat: 3.25, duration: 0.75, velocity: 85 },
      { pitch: 67, startBeat: 4, duration: 1, velocity: 82 },
      { pitch: 62, startBeat: 5, duration: 0.5, velocity: 75 },
      { pitch: 71, startBeat: 5.5, duration: 1.5, velocity: 90 },
      { pitch: 69, startBeat: 7, duration: 1, velocity: 80 },
    ],
  },
  {
    id: 'melody-4',
    qualityScore: 81,
    explanation:
      'Surprise melody — the algorithm chose a pentatonic-first approach then introduced a single chromatic note (Eb) that creates a brief moment of bittersweetness. Long note durations make each pitch feel intentional and weighted. Designed for a synth lead with slow attack, where each note blooms.',
    emotionTags: ['bittersweet', 'contemplative', 'spacious'],
    contour: 'arch',
    articulation: 'legato',
    notes: [
      { pitch: 62, startBeat: 0, duration: 2, velocity: 80 },
      { pitch: 65, startBeat: 2, duration: 1, velocity: 82 },
      { pitch: 69, startBeat: 3, duration: 1, velocity: 88 },
      { pitch: 63, startBeat: 4, duration: 1.5, velocity: 85 },
      { pitch: 62, startBeat: 5.5, duration: 1, velocity: 80 },
      { pitch: 60, startBeat: 6.5, duration: 1.5, velocity: 75 },
    ],
  },
  {
    id: 'melody-5',
    qualityScore: 76,
    explanation:
      'A tighter, motif-based approach. The same 3-note cell (D–F–A) repeats with rhythmic variation — displaced by half a beat each repetition creating a feeling of rotation. On the final bar, the motif inverts. Simple enough to stay out of the way of a vocal, complex enough to hold interest as a counter-melody.',
    emotionTags: ['hypnotic', 'repetitive', 'grounding'],
    contour: 'wave',
    articulation: 'staccato',
    notes: [
      { pitch: 62, startBeat: 0, duration: 0.5, velocity: 88 },
      { pitch: 65, startBeat: 0.5, duration: 0.25, velocity: 82 },
      { pitch: 69, startBeat: 0.75, duration: 0.25, velocity: 85 },
      { pitch: 62, startBeat: 1.5, duration: 0.5, velocity: 88 },
      { pitch: 65, startBeat: 2, duration: 0.25, velocity: 82 },
      { pitch: 69, startBeat: 2.25, duration: 0.25, velocity: 85 },
      { pitch: 62, startBeat: 3, duration: 0.5, velocity: 88 },
      { pitch: 65, startBeat: 3.5, duration: 0.25, velocity: 82 },
      { pitch: 69, startBeat: 3.75, duration: 0.5, velocity: 85 },
      { pitch: 69, startBeat: 4.5, duration: 0.5, velocity: 82 },
      { pitch: 65, startBeat: 5, duration: 0.25, velocity: 78 },
      { pitch: 62, startBeat: 5.25, duration: 0.25, velocity: 85 },
      { pitch: 69, startBeat: 6, duration: 0.5, velocity: 82 },
      { pitch: 65, startBeat: 6.5, duration: 0.25, velocity: 78 },
      { pitch: 62, startBeat: 6.75, duration: 1.25, velocity: 80 },
    ],
  },
]
