import type { Song, Folder, Tag } from '@/types'

export const mockTags: Tag[] = [
  { id: 'tag-1', name: 'Trap', color: '#bf5af2' },
  { id: 'tag-2', name: 'Dark', color: '#ff453a' },
  { id: 'tag-3', name: 'Melodic', color: '#0a84ff' },
  { id: 'tag-4', name: 'Hard', color: '#ff9f0a' },
  { id: 'tag-5', name: 'Chill', color: '#32d74b' },
]

export const mockFolders: Folder[] = [
  { id: 'folder-1', name: 'Album 1', createdAt: '2024-01-15T10:00:00Z' },
  { id: 'folder-2', name: 'Singles', createdAt: '2024-02-01T10:00:00Z' },
  { id: 'folder-3', name: 'Collabs', createdAt: '2024-03-10T10:00:00Z' },
]

export const mockSongs: Song[] = [
  {
    id: 'song-1',
    name: 'Midnight Operator',
    bpm: 140,
    key: 'F# minor',
    timeSignature: '4/4',
    genre: 'Trap',
    status: 'in_progress',
    currentPhase: 'chords',
    folderId: 'folder-1',
    notes: 'Dark melodic trap. Heavy 808s. Reference: Playboi Carti vibes.',
    createdAt: '2024-11-01T08:00:00Z',
    updatedAt: '2024-11-20T14:30:00Z',
    tags: [mockTags[0], mockTags[1]],
  },
  {
    id: 'song-2',
    name: 'Ghost Protocol',
    bpm: 155,
    key: 'D minor',
    timeSignature: '4/4',
    genre: 'Trap',
    status: 'in_progress',
    currentPhase: 'engineering',
    folderId: 'folder-2',
    notes: 'Aggressive. Fast hi-hat rolls. Snare reverb heavy.',
    createdAt: '2024-10-15T09:00:00Z',
    updatedAt: '2024-11-18T11:00:00Z',
    tags: [mockTags[0], mockTags[3]],
  },
  {
    id: 'song-3',
    name: 'Neon Cascade',
    bpm: 128,
    key: 'C minor',
    timeSignature: '4/4',
    genre: 'Melodic Trap',
    status: 'complete',
    currentPhase: undefined,
    folderId: 'folder-2',
    notes: 'Finished. Melodic synths over hard drums.',
    createdAt: '2024-09-05T10:00:00Z',
    updatedAt: '2024-10-30T16:00:00Z',
    tags: [mockTags[2], mockTags[0]],
  },
  {
    id: 'song-4',
    name: 'Void Walker',
    bpm: 145,
    key: 'G minor',
    timeSignature: '4/4',
    genre: 'Trap',
    status: 'on_hold',
    currentPhase: 'melody',
    folderId: 'folder-1',
    notes: 'On pause. Need better chord progression.',
    createdAt: '2024-08-20T10:00:00Z',
    updatedAt: '2024-09-15T12:00:00Z',
    tags: [mockTags[1]],
  },
  {
    id: 'song-5',
    name: 'Solar Drift',
    bpm: 120,
    key: 'A minor',
    timeSignature: '4/4',
    genre: 'Melodic Trap',
    status: 'in_progress',
    currentPhase: 'lyrics',
    folderId: 'folder-3',
    notes: 'Collab. Softer, more melodic approach.',
    createdAt: '2024-11-05T10:00:00Z',
    updatedAt: '2024-11-21T09:00:00Z',
    tags: [mockTags[2], mockTags[4]],
  },
]
